# -*- coding: utf-8 -*-
"""AI-Powered Emoji Recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L7zkTpPIGAT1e0q2VwCXKIVvNL_uON0s
"""

import random
import gradio as gr

# Extended keyword → emoji dictionary
emoji_dict = {
    # Emotions
    "happy": ["😄", "😁", "😎", "😊", "🤩", "🥳", "😂"],
    "sad": ["😢", "😞", "😔", "🥺", "😓", "😭"],
    "love": ["❤️", "😍", "🥰", "💖", "💘", "💕"],
    "angry": ["😡", "😠", "🤬", "😤"],
    "surprised": ["😲", "😳", "😮", "😯"],
    "confused": ["🤔", "😕", "😣", "😖"],

    # Food & Drinks
    "pizza": ["🍕", "😋"],
    "burger": ["🍔", "😋"],
    "fries": ["🍟", "😋"],
    "coffee": ["☕", "😴"],
    "tea": ["🍵", "😌"],
    "cake": ["🍰", "🎂", "😋"],
    "icecream": ["🍦", "🍨", "😋"],

    # Animals
    "cat": ["🐱", "😺", "🐈", "😹"],
    "dog": ["🐶", "🐕", "🦮", "🐩"],
    "bird": ["🐦", "🐤", "🕊️"],
    "fish": ["🐟", "🐠", "🐡"],
    "lion": ["🦁", "🐾"],

    # Activities & Fun
    "party": ["🎉", "🥳", "🎊", "💃", "🕺"],
    "game": ["🎮", "🕹️", "♟️"],
    "music": ["🎵", "🎶", "🎸", "🎹"],
    "travel": ["✈️", "🗺️", "🏖️", "🚗", "🚆"],
    "movie": ["🎬", "🍿", "📽️"],

    # Nature & Weather
    "sun": ["☀️", "🌞", "🌻"],
    "moon": ["🌙", "🌚", "🌝"],
    "rain": ["🌧️", "☔", "💧"],
    "snow": ["❄️", "⛄", "☃️"],
    "flower": ["🌸", "🌹", "🌼", "🌺"],

    # Random / Misc
    "fire": ["🔥", "💥", "⚡"],
    "star": ["⭐", "🌟", "✨"],
    "gift": ["🎁", "🎀", "🎉"],
    "money": ["💰", "💵", "🤑", "💸"],
    "heart": ["❤️", "💖", "💗", "💓"],
}

def recommend_emojis(text):
    emojis = []
    for word in text.lower().replace(",", "").replace(".", "").split():
        if word in emoji_dict:
            emojis.extend(emoji_dict[word])
    if not emojis:
        emojis = ["🤔", "❓", "💭"]
    return " ".join(random.sample(emojis, min(5, len(emojis))))

iface = gr.Interface(fn=recommend_emojis,
                     inputs=gr.Textbox(lines=2, placeholder="Type your text..."),
                     outputs="text",
                     title="AI Emoji Recommender")
iface.launch()